issues:
  exclude-rules:
    - path: token.go
      linters:
        - errcheck
    - path: escape.go
      linters:
        - errcheck

    - path: xxhash.go
      linters:
        - deadcode
        - unused

    - linters:
        - typecheck
      text: "syscall/js"

